version: '3.2'

services:
  assessment_service:
    build:
      context: ./assessment-service
    container_name: assessment_service
    depends_on:
      - kafka
      - mysql_db
    ports:
      - 8080:8080
      - 8787:8787
    links:
      - mysql_db:app_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/assessment-service/api/engineering/ping"]
      interval: 5s
      timeout: 2s
      retries: 200
  assessment_api:
    build:
      context: ./assessment-api
    container_name: assessment_api
    depends_on:
      - kafka
    ports:
      - 8081:8080
      - 8788:8787
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/assessment-api/api/engineering/ping"]
      interval: 5s
      timeout: 2s
      retries: 200
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://192.168.0.103:9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    depends_on:
      - zookeeper
    volumes:
      - ./:/etc/kafka
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app_assm_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

volumes:
  db:

networks:
  default:
    external:
      name: assessment_net
